version: '3.8'

services:
  index:
    build:
      context: ./fronts/index
    container_name: index_app
    networks:
      - app-network
    ports:
      - "3000:80"

  treejs:
    build:
      context: ./fronts/treeJS
    container_name: treeJS_app
    networks:
      - app-network
    ports:
      - "3001:80"

  nginx:
    image: nginx:alpine
    container_name: nginx_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - index
      - treejs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
